### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by alextall**
@initFabian I upgraded the Swift version, and to make it easier to update in the future, it is only declared at the project level. All targets will inherit from the one setting.

As noted in the previous PR, this should be tagged as a new release. No code changes were needed from Swift 4.2, so I would think this can be v2.2, but upgrading to Swift 5 could be considered a breaking change, so v3.0 is also a viable option.

### CODE REVIEW

**Comment by alextall** [comment]
@initFabian If you want to update CI to Swift 5, I’d expect tests to continue to pass. Then we can merge this puppy, and cut a new release.

**Comment by initFabian** [comment]
Whats the status of this PR? is it simply merging and deploying a new build?

**Comment by initFabian** [comment]
Will this address #33?

**Comment by alextall** [comment]
Yes. This should resolve #33, and it’s ready to merge.

**Pull request merged**
